"""generate more columns for pipeline_runs table

Revision ID: 063da6b72236
Revises: ee92de2b12a3
Create Date: 2026-09-24 22:29:04.633491

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '063da6b72236'
down_revision: Union[str, None] = 'ee92de2b12a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_runs', sa.Column('source_type', sa.String(length=32), nullable=True))
    op.add_column('pipeline_runs', sa.Column('mode', sa.String(length=16), nullable=True))
    op.add_column('pipeline_runs', sa.Column('event_key', sa.String(length=64), nullable=True))
    op.add_column('pipeline_runs', sa.Column('event_id', sa.UUID(), nullable=True))
    op.add_column('pipeline_runs', sa.Column('show_date', sa.Date(), nullable=True))
    op.create_index('idx_pipeline_runs_event_id', 'pipeline_runs', ['event_id'], unique=False)
    op.create_index('idx_pipeline_runs_event_key', 'pipeline_runs', ['event_key'], unique=False)
    op.create_index('idx_pipeline_runs_show_date', 'pipeline_runs', ['show_date'], unique=False)
    op.create_index('idx_pipeline_runs_source_type', 'pipeline_runs', ['source_type'], unique=False)
    op.create_foreign_key('fk_pipeline_runs_event_id', 'pipeline_runs', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_pipeline_runs_event_id', 'pipeline_runs', type_='foreignkey')
    op.drop_index('idx_pipeline_runs_source_type', table_name='pipeline_runs')
    op.drop_index('idx_pipeline_runs_show_date', table_name='pipeline_runs')
    op.drop_index('idx_pipeline_runs_event_key', table_name='pipeline_runs')
    op.drop_index('idx_pipeline_runs_event_id', table_name='pipeline_runs')
    op.drop_column('pipeline_runs', 'show_date')
    op.drop_column('pipeline_runs', 'event_id')
    op.drop_column('pipeline_runs', 'event_key')
    op.drop_column('pipeline_runs', 'mode')
    op.drop_column('pipeline_runs', 'source_type')
    # ### end Alembic commands ###
