"""create initial schema

Revision ID: 22c558ee68cb
Revises: 
Create Date: 2026-08-08 02:40:10.964824

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '22c558ee68cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_records', sa.BigInteger(), nullable=True),
    sa.Column('success_count', sa.BigInteger(), nullable=True),
    sa.Column('error_count', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_runs_created_at', 'pipeline_runs', ['created_at'], unique=False)
    op.create_index('idx_pipeline_runs_lstarted_at', 'pipeline_runs', ['started_at'], unique=False)
    op.create_table('veld_2026_raw_extract',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('fb_listing_id', sa.Text(), nullable=False),
    sa.Column('listing_url', sa.Text(), nullable=False),
    sa.Column('seller_profile_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('location_city', sa.Text(), nullable=True),
    sa.Column('location_state', sa.Text(), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name='fk_veld_2026_raw_run_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_veld_2026_raw_current_url', 'veld_2026_raw_extract', ['listing_url'], unique=False, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_index('idx_veld_2026_raw_fb_listing_id', 'veld_2026_raw_extract', ['fb_listing_id'], unique=False)
    op.create_index('idx_veld_2026_raw_listed_at', 'veld_2026_raw_extract', ['listed_at'], unique=False)
    op.create_index('idx_veld_2026_raw_run', 'veld_2026_raw_extract', ['pipeline_run_id'], unique=False)
    op.create_table('veld_2026_transformed',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('raw_id', sa.BigInteger(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('fb_listing_id', sa.Text(), nullable=False),
    sa.Column('listing_url', sa.Text(), nullable=False),
    sa.Column('seller_profile_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_per_unit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('location_city', sa.Text(), nullable=True),
    sa.Column('location_state', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('ticket_type', sa.String(length=32), nullable=False),
    sa.Column('event_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('listing_type', sa.String(length=32), nullable=False),
    sa.Column('is_relevant', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name='fk_veld_2026_transformed_run_id'),
    sa.ForeignKeyConstraint(['raw_id'], ['veld_2026_raw_extract.id'], name='fk_veld_2026_transformed_raw_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_id', name='uq_veld_2026_transformed_raw_id')
    )
    op.create_index('idx_veld_2026_transformed_listed_at', 'veld_2026_transformed', ['listed_at'], unique=False)
    op.create_index('idx_veld_2026_transformed_listing_id', 'veld_2026_transformed', ['fb_listing_id'], unique=False)
    op.create_index('idx_veld_2026_transformed_location_city', 'veld_2026_transformed', ['location_city'], unique=False)
    op.create_index('idx_veld_2026_transformed_pipeline_run', 'veld_2026_transformed', ['pipeline_run_id'], unique=False)
    op.create_index('idx_veld_2026_transformed_price', 'veld_2026_transformed', ['price'], unique=False)
    op.create_index('idx_veld_2026_transformed_seller', 'veld_2026_transformed', ['seller_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_veld_2026_transformed_seller', table_name='veld_2026_transformed')
    op.drop_index('idx_veld_2026_transformed_price', table_name='veld_2026_transformed')
    op.drop_index('idx_veld_2026_transformed_pipeline_run', table_name='veld_2026_transformed')
    op.drop_index('idx_veld_2026_transformed_location_city', table_name='veld_2026_transformed')
    op.drop_index('idx_veld_2026_transformed_listing_id', table_name='veld_2026_transformed')
    op.drop_index('idx_veld_2026_transformed_listed_at', table_name='veld_2026_transformed')
    op.drop_table('veld_2026_transformed')
    op.drop_index('idx_veld_2026_raw_run', table_name='veld_2026_raw_extract')
    op.drop_index('idx_veld_2026_raw_listed_at', table_name='veld_2026_raw_extract')
    op.drop_index('idx_veld_2026_raw_fb_listing_id', table_name='veld_2026_raw_extract')
    op.drop_index('idx_veld_2026_raw_current_url', table_name='veld_2026_raw_extract', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_table('veld_2026_raw_extract')
    op.drop_index('idx_pipeline_runs_lstarted_at', table_name='pipeline_runs')
    op.drop_index('idx_pipeline_runs_created_at', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
