"""make the classify table

Revision ID: 3e833675849f
Revises: e5b05e11a9f7
Create Date: 2026-08-29 16:02:48.488452

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3e833675849f'
down_revision: Union[str, None] = 'e5b05e11a9f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facebook_listing_classifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('raw_listing_id', sa.BigInteger(), nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('llm_model', sa.Text(), nullable=False),
    sa.Column('is_ticket', sa.Boolean(), nullable=False),
    sa.Column('is_buyer_listing', sa.Boolean(), nullable=False),
    sa.Column('is_merch', sa.Boolean(), nullable=False),
    sa.Column('is_wrong_category', sa.Boolean(), nullable=False),
    sa.Column('extracted_event', sa.Text(), nullable=True),
    sa.Column('extracted_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('face_value_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('face_value_mentioned', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('ticket_type', sa.String(length=30), nullable=True),
    sa.Column('event_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_negotiable', sa.Boolean(), nullable=False),
    sa.Column('includes_extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seller_note', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('raw_llm_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['raw_listing_id'], ['facebook_listing_raw.id'], name='fk_fb_classification_raw'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_listing_id', name='uq_fb_classification_raw_listing')
    )
    op.create_index('idx_fb_classification_classified_at', 'facebook_listing_classifications', ['classified_at'], unique=False)
    op.create_index('idx_fb_classification_is_ticket', 'facebook_listing_classifications', ['is_ticket'], unique=False)
    op.create_index('idx_fb_classification_raw_listing_id', 'facebook_listing_classifications', ['raw_listing_id'], unique=False)
    op.drop_index(op.f('idx_fb_listing_transformed_event_city'), table_name='facebook_listing_transformed')
    op.drop_index(op.f('idx_fb_listing_transformed_event_listed_at'), table_name='facebook_listing_transformed')
    op.drop_index(op.f('idx_fb_listing_transformed_event_listing'), table_name='facebook_listing_transformed')
    op.drop_index(op.f('idx_fb_listing_transformed_event_price'), table_name='facebook_listing_transformed')
    op.drop_index(op.f('idx_fb_listing_transformed_pipeline_run'), table_name='facebook_listing_transformed')
    op.drop_index(op.f('idx_fb_listing_transformed_seller'), table_name='facebook_listing_transformed')
    op.drop_table('facebook_listing_transformed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facebook_listing_transformed',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('raw_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fb_listing_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('listing_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('seller_profile_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('is_sold', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('listed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('scraped_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('price_per_unit', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('price_is_anomaly', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('location_city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_state', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ticket_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('event_days', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('listing_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('is_relevant', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('event_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_transformed_event_id')),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name=op.f('fk_transformed_run_id')),
    sa.ForeignKeyConstraint(['raw_id'], ['facebook_listing_raw.id'], name=op.f('fk_transformed_raw_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('transformed_pkey')),
    sa.UniqueConstraint('raw_id', name=op.f('uq_fb_listing_transformed_raw_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_fb_listing_transformed_seller'), 'facebook_listing_transformed', ['seller_profile_id'], unique=False)
    op.create_index(op.f('idx_fb_listing_transformed_pipeline_run'), 'facebook_listing_transformed', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('idx_fb_listing_transformed_event_price'), 'facebook_listing_transformed', ['event_id', 'price'], unique=False)
    op.create_index(op.f('idx_fb_listing_transformed_event_listing'), 'facebook_listing_transformed', ['event_id', 'fb_listing_id'], unique=False)
    op.create_index(op.f('idx_fb_listing_transformed_event_listed_at'), 'facebook_listing_transformed', ['event_id', 'listed_at'], unique=False)
    op.create_index(op.f('idx_fb_listing_transformed_event_city'), 'facebook_listing_transformed', ['event_id', 'location_city'], unique=False)
    op.drop_index('idx_fb_classification_raw_listing_id', table_name='facebook_listing_classifications')
    op.drop_index('idx_fb_classification_is_ticket', table_name='facebook_listing_classifications')
    op.drop_index('idx_fb_classification_classified_at', table_name='facebook_listing_classifications')
    op.drop_table('facebook_listing_classifications')
    # ### end Alembic commands ###
