"""updating the db with generalized tables for all events

Revision ID: 700c170a1526
Revises: 
Create Date: 2026-08-14 18:18:37.615039

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '700c170a1526'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_key', sa.String(length=64), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_records', sa.BigInteger(), nullable=True),
    sa.Column('error_count', sa.BigInteger(), nullable=True),
    sa.Column('newly_added_count', sa.BigInteger(), nullable=True),
    sa.Column('change_added_count', sa.BigInteger(), nullable=True),
    sa.Column('skipped_count', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_runs_created_at', 'pipeline_runs', ['created_at'], unique=False)
    op.create_index('idx_pipeline_runs_lstarted_at', 'pipeline_runs', ['started_at'], unique=False)
    op.create_table('raw_extract',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('fb_listing_id', sa.Text(), nullable=False),
    sa.Column('listing_url', sa.Text(), nullable=False),
    sa.Column('seller_profile_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('location_city', sa.Text(), nullable=True),
    sa.Column('location_state', sa.Text(), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='fk_raw_extract_event_id'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name='fk_raw_extract_run_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_extract_current_listing', 'raw_extract', ['event_id', 'fb_listing_id'], unique=True, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_index('idx_raw_extract_event_listed_at', 'raw_extract', ['event_id', 'listed_at'], unique=False)
    op.create_index('idx_raw_extract_event_listing', 'raw_extract', ['event_id', 'fb_listing_id'], unique=False)
    op.create_index('idx_raw_extract_run', 'raw_extract', ['pipeline_run_id'], unique=False)
    op.create_table('transformed',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('raw_id', sa.BigInteger(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('fb_listing_id', sa.Text(), nullable=False),
    sa.Column('listing_url', sa.Text(), nullable=False),
    sa.Column('seller_profile_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_per_unit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('location_city', sa.Text(), nullable=True),
    sa.Column('location_state', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('ticket_type', sa.String(length=32), nullable=False),
    sa.Column('event_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('listing_type', sa.String(length=32), nullable=False),
    sa.Column('is_relevant', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='fk_transformed_event_id'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name='fk_transformed_run_id'),
    sa.ForeignKeyConstraint(['raw_id'], ['raw_extract.id'], name='fk_transformed_raw_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_id', name='uq_transformed_raw_id')
    )
    op.create_index('idx_transformed_event_city', 'transformed', ['event_id', 'location_city'], unique=False)
    op.create_index('idx_transformed_event_listed_at', 'transformed', ['event_id', 'listed_at'], unique=False)
    op.create_index('idx_transformed_event_listing_id', 'transformed', ['event_id', 'fb_listing_id'], unique=False)
    op.create_index('idx_transformed_event_price', 'transformed', ['event_id', 'price'], unique=False)
    op.create_index('idx_transformed_pipeline_run', 'transformed', ['pipeline_run_id'], unique=False)
    op.create_index('idx_transformed_seller', 'transformed', ['seller_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transformed_seller', table_name='transformed')
    op.drop_index('idx_transformed_pipeline_run', table_name='transformed')
    op.drop_index('idx_transformed_event_price', table_name='transformed')
    op.drop_index('idx_transformed_event_listing_id', table_name='transformed')
    op.drop_index('idx_transformed_event_listed_at', table_name='transformed')
    op.drop_index('idx_transformed_event_city', table_name='transformed')
    op.drop_table('transformed')
    op.drop_index('idx_raw_extract_run', table_name='raw_extract')
    op.drop_index('idx_raw_extract_event_listing', table_name='raw_extract')
    op.drop_index('idx_raw_extract_event_listed_at', table_name='raw_extract')
    op.drop_index('idx_raw_extract_current_listing', table_name='raw_extract', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_table('raw_extract')
    op.drop_index('idx_pipeline_runs_lstarted_at', table_name='pipeline_runs')
    op.drop_index('idx_pipeline_runs_created_at', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_table('events')
    # ### end Alembic commands ###
