"""add modules for apify scraper

Revision ID: 99659acfb2d9
Revises: c193b850ed3b
Create Date: 2026-08-12 17:45:34.225646

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '99659acfb2d9'
down_revision: Union[str, None] = 'c193b850ed3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('veld_2026_raw_extract', sa.Column('currency', sa.String(length=10), nullable=True))
    op.drop_index(op.f('idx_veld_2026_raw_current_url'), table_name='veld_2026_raw_extract', postgresql_where='(valid_to IS NULL)')
    op.create_index('idx_veld_2026_raw_current_listing', 'veld_2026_raw_extract', ['fb_listing_id'], unique=True, postgresql_where=sa.text('valid_to IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_veld_2026_raw_current_listing', table_name='veld_2026_raw_extract', postgresql_where=sa.text('valid_to IS NULL'))
    op.create_index(op.f('idx_veld_2026_raw_current_url'), 'veld_2026_raw_extract', ['listing_url'], unique=True, postgresql_where='(valid_to IS NULL)')
    op.drop_column('veld_2026_raw_extract', 'currency')
    # ### end Alembic commands ###
