"""make partial index unique

Revision ID: c193b850ed3b
Revises: da1e2b76bfa5
Create Date: 2026-08-10 16:55:00.951208

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = 'c193b850ed3b'
down_revision: Union[str, None] = 'da1e2b76bfa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_veld_2026_raw_current_url'), table_name='veld_2026_raw_extract', postgresql_where='(valid_to IS NULL)')
    op.create_index('idx_veld_2026_raw_current_url', 'veld_2026_raw_extract', ['listing_url'], unique=True, postgresql_where=sa.text('valid_to IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_veld_2026_raw_current_url', table_name='veld_2026_raw_extract', postgresql_where=sa.text('valid_to IS NULL'))
    op.create_index(op.f('idx_veld_2026_raw_current_url'), 'veld_2026_raw_extract', ['listing_url'], unique=False, postgresql_where='(valid_to IS NULL)')
    # ### end Alembic commands ###
