"""add module to extract from seatgeek as a source

Revision ID: c81d98f60361
Revises: 3e833675849f
Create Date: 2026-09-02 22:00:55.963163

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c81d98f60361'
down_revision: Union[str, None] = '3e833675849f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seatgeek_listing_raw',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_key', sa.String(length=64), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('sg_listing_id', sa.Text(), nullable=False),
    sa.Column('sg_event_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.Text(), nullable=True),
    sa.Column('row', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_ticket', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deal_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('delivery_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='fk_sg_listing_raw_event_id'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name='fk_sg_listing_raw_run_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sg_listing_raw_current_listing', 'seatgeek_listing_raw', ['event_id', 'sg_listing_id'], unique=True, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_index('idx_sg_listing_raw_event_listing', 'seatgeek_listing_raw', ['event_id', 'sg_listing_id'], unique=False)
    op.create_index('idx_sg_listing_raw_run', 'seatgeek_listing_raw', ['pipeline_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sg_listing_raw_run', table_name='seatgeek_listing_raw')
    op.drop_index('idx_sg_listing_raw_event_listing', table_name='seatgeek_listing_raw')
    op.drop_index('idx_sg_listing_raw_current_listing', table_name='seatgeek_listing_raw', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_table('seatgeek_listing_raw')
    # ### end Alembic commands ###
