"""split pipeline run counts

Revision ID: da1e2b76bfa5
Revises: 22c558ee68cb
Create Date: 2026-08-10 16:01:23.529740

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = 'da1e2b76bfa5'
down_revision: Union[str, None] = '22c558ee68cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_runs', sa.Column('newly_added_count', sa.BigInteger(), nullable=True))
    op.add_column('pipeline_runs', sa.Column('change_added_count', sa.BigInteger(), nullable=True))
    op.add_column('pipeline_runs', sa.Column('skipped_count', sa.BigInteger(), nullable=True))
    op.drop_column('pipeline_runs', 'success_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_runs', sa.Column('success_count', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('pipeline_runs', 'skipped_count')
    op.drop_column('pipeline_runs', 'change_added_count')
    op.drop_column('pipeline_runs', 'newly_added_count')
    # ### end Alembic commands ###
