"""check_drift

Revision ID: df5e0a84e263
Revises: ee92de2b12a3
Create Date: 2026-09-17 23:49:58.824851

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'df5e0a84e263'
down_revision: Union[str, None] = 'ee92de2b12a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_key', sa.String(length=64), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key'),
    schema='public'
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_records', sa.BigInteger(), nullable=True),
    sa.Column('error_count', sa.BigInteger(), nullable=True),
    sa.Column('newly_added_count', sa.BigInteger(), nullable=True),
    sa.Column('change_added_count', sa.BigInteger(), nullable=True),
    sa.Column('skipped_count', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_pipeline_runs_created_at', 'pipeline_runs', ['created_at'], unique=False, schema='public')
    op.create_index('idx_pipeline_runs_lstarted_at', 'pipeline_runs', ['started_at'], unique=False, schema='public')
    op.create_table('seatgeek_event_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_key', sa.String(length=64), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('sg_event_id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('lowest_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('highest_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('average_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('median_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('listing_count', sa.Integer(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['public.events.id'], name='fk_sg_event_stats_event_id'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['public.pipeline_runs.id'], name='fk_sg_event_stats_run_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'stat_date', name='uq_sg_event_stats_event_date'),
    schema='public'
    )
    op.create_index('idx_sg_event_stats_run', 'seatgeek_event_stats', ['pipeline_run_id'], unique=False, schema='public')
    op.drop_constraint(op.f('fk_fb_listing_raw_run_id'), 'facebook_listings_legacy_raw', schema='facebook', type_='foreignkey')
    op.drop_constraint(op.f('fk_fb_listing_raw_event_id'), 'facebook_listings_legacy_raw', schema='facebook', type_='foreignkey')
    op.create_foreign_key('fk_fb_listing_raw_event_id', 'facebook_listings_legacy_raw', 'events', ['event_id'], ['id'], source_schema='facebook', referent_schema='public')
    op.create_foreign_key('fk_fb_listing_raw_run_id', 'facebook_listings_legacy_raw', 'pipeline_runs', ['pipeline_run_id'], ['id'], source_schema='facebook', referent_schema='public')
    op.drop_constraint(op.f('fk_fb_mkt_listing_raw_event_id'), 'facebook_listings_new_raw', schema='facebook', type_='foreignkey')
    op.drop_constraint(op.f('fk_fb_mkt_listing_raw_run_id'), 'facebook_listings_new_raw', schema='facebook', type_='foreignkey')
    op.create_foreign_key('fk_fb_mkt_listing_raw_event_id', 'facebook_listings_new_raw', 'events', ['event_id'], ['id'], source_schema='facebook', referent_schema='public')
    op.create_foreign_key('fk_fb_mkt_listing_raw_run_id', 'facebook_listings_new_raw', 'pipeline_runs', ['pipeline_run_id'], ['id'], source_schema='facebook', referent_schema='public')
    op.drop_constraint(op.f('fk_sh_listing_raw_run_id'), 'listing_raw', schema='stubhub', type_='foreignkey')
    op.drop_constraint(op.f('fk_sh_listing_raw_event_id'), 'listing_raw', schema='stubhub', type_='foreignkey')
    op.create_foreign_key('fk_sh_listing_raw_run_id', 'listing_raw', 'pipeline_runs', ['pipeline_run_id'], ['id'], source_schema='stubhub', referent_schema='public')
    op.create_foreign_key('fk_sh_listing_raw_event_id', 'listing_raw', 'events', ['event_id'], ['id'], source_schema='stubhub', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sh_listing_raw_event_id', 'listing_raw', schema='stubhub', type_='foreignkey')
    op.drop_constraint('fk_sh_listing_raw_run_id', 'listing_raw', schema='stubhub', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sh_listing_raw_event_id'), 'listing_raw', 'events', ['event_id'], ['id'], source_schema='stubhub')
    op.create_foreign_key(op.f('fk_sh_listing_raw_run_id'), 'listing_raw', 'pipeline_runs', ['pipeline_run_id'], ['id'], source_schema='stubhub')
    op.drop_constraint('fk_fb_mkt_listing_raw_run_id', 'facebook_listings_new_raw', schema='facebook', type_='foreignkey')
    op.drop_constraint('fk_fb_mkt_listing_raw_event_id', 'facebook_listings_new_raw', schema='facebook', type_='foreignkey')
    op.create_foreign_key(op.f('fk_fb_mkt_listing_raw_run_id'), 'facebook_listings_new_raw', 'pipeline_runs', ['pipeline_run_id'], ['id'], source_schema='facebook')
    op.create_foreign_key(op.f('fk_fb_mkt_listing_raw_event_id'), 'facebook_listings_new_raw', 'events', ['event_id'], ['id'], source_schema='facebook')
    op.drop_constraint('fk_fb_listing_raw_run_id', 'facebook_listings_legacy_raw', schema='facebook', type_='foreignkey')
    op.drop_constraint('fk_fb_listing_raw_event_id', 'facebook_listings_legacy_raw', schema='facebook', type_='foreignkey')
    op.create_foreign_key(op.f('fk_fb_listing_raw_event_id'), 'facebook_listings_legacy_raw', 'events', ['event_id'], ['id'], source_schema='facebook')
    op.create_foreign_key(op.f('fk_fb_listing_raw_run_id'), 'facebook_listings_legacy_raw', 'pipeline_runs', ['pipeline_run_id'], ['id'], source_schema='facebook')
    op.drop_index('idx_sg_event_stats_run', table_name='seatgeek_event_stats', schema='public')
    op.drop_table('seatgeek_event_stats', schema='public')
    op.drop_index('idx_pipeline_runs_lstarted_at', table_name='pipeline_runs', schema='public')
    op.drop_index('idx_pipeline_runs_created_at', table_name='pipeline_runs', schema='public')
    op.drop_table('pipeline_runs', schema='public')
    op.drop_table('events', schema='public')
    # ### end Alembic commands ###
