"""modify namings

Revision ID: e5b05e11a9f7
Revises: f3a1d2e4b5c6
Create Date: 2026-08-17 19:14:54.077138

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = 'e5b05e11a9f7'
down_revision: Union[str, None] = 'f3a1d2e4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_raw_extract_current_listing'), table_name='facebook_listing_raw', postgresql_where='(valid_to IS NULL)')
    op.drop_index(op.f('idx_raw_extract_event_listed_at'), table_name='facebook_listing_raw')
    op.drop_index(op.f('idx_raw_extract_event_listing'), table_name='facebook_listing_raw')
    op.drop_index(op.f('idx_raw_extract_run'), table_name='facebook_listing_raw')
    op.create_index('idx_fb_listing_raw_current_listing', 'facebook_listing_raw', ['event_id', 'fb_listing_id'], unique=True, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_index('idx_fb_listing_raw_event_listed_at', 'facebook_listing_raw', ['event_id', 'listed_at'], unique=False)
    op.create_index('idx_fb_listing_raw_event_listing', 'facebook_listing_raw', ['event_id', 'fb_listing_id'], unique=False)
    op.create_index('idx_fb_listing_raw_run', 'facebook_listing_raw', ['pipeline_run_id'], unique=False)
    op.drop_index(op.f('idx_transformed_event_city'), table_name='facebook_listing_transformed')
    op.drop_index(op.f('idx_transformed_event_listed_at'), table_name='facebook_listing_transformed')
    op.drop_index(op.f('idx_transformed_event_listing_id'), table_name='facebook_listing_transformed')
    op.drop_index(op.f('idx_transformed_event_price'), table_name='facebook_listing_transformed')
    op.drop_index(op.f('idx_transformed_pipeline_run'), table_name='facebook_listing_transformed')
    op.drop_index(op.f('idx_transformed_seller'), table_name='facebook_listing_transformed')
    op.drop_constraint(op.f('uq_transformed_raw_id'), 'facebook_listing_transformed', type_='unique')
    op.create_index('idx_fb_listing_transformed_event_city', 'facebook_listing_transformed', ['event_id', 'location_city'], unique=False)
    op.create_index('idx_fb_listing_transformed_event_listed_at', 'facebook_listing_transformed', ['event_id', 'listed_at'], unique=False)
    op.create_index('idx_fb_listing_transformed_event_listing', 'facebook_listing_transformed', ['event_id', 'fb_listing_id'], unique=False)
    op.create_index('idx_fb_listing_transformed_event_price', 'facebook_listing_transformed', ['event_id', 'price'], unique=False)
    op.create_index('idx_fb_listing_transformed_pipeline_run', 'facebook_listing_transformed', ['pipeline_run_id'], unique=False)
    op.create_index('idx_fb_listing_transformed_seller', 'facebook_listing_transformed', ['seller_profile_id'], unique=False)
    op.create_unique_constraint('uq_fb_listing_transformed_raw_id', 'facebook_listing_transformed', ['raw_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_fb_listing_transformed_raw_id', 'facebook_listing_transformed', type_='unique')
    op.drop_index('idx_fb_listing_transformed_seller', table_name='facebook_listing_transformed')
    op.drop_index('idx_fb_listing_transformed_pipeline_run', table_name='facebook_listing_transformed')
    op.drop_index('idx_fb_listing_transformed_event_price', table_name='facebook_listing_transformed')
    op.drop_index('idx_fb_listing_transformed_event_listing', table_name='facebook_listing_transformed')
    op.drop_index('idx_fb_listing_transformed_event_listed_at', table_name='facebook_listing_transformed')
    op.drop_index('idx_fb_listing_transformed_event_city', table_name='facebook_listing_transformed')
    op.create_unique_constraint(op.f('uq_transformed_raw_id'), 'facebook_listing_transformed', ['raw_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_transformed_seller'), 'facebook_listing_transformed', ['seller_profile_id'], unique=False)
    op.create_index(op.f('idx_transformed_pipeline_run'), 'facebook_listing_transformed', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('idx_transformed_event_price'), 'facebook_listing_transformed', ['event_id', 'price'], unique=False)
    op.create_index(op.f('idx_transformed_event_listing_id'), 'facebook_listing_transformed', ['event_id', 'fb_listing_id'], unique=False)
    op.create_index(op.f('idx_transformed_event_listed_at'), 'facebook_listing_transformed', ['event_id', 'listed_at'], unique=False)
    op.create_index(op.f('idx_transformed_event_city'), 'facebook_listing_transformed', ['event_id', 'location_city'], unique=False)
    op.drop_index('idx_fb_listing_raw_run', table_name='facebook_listing_raw')
    op.drop_index('idx_fb_listing_raw_event_listing', table_name='facebook_listing_raw')
    op.drop_index('idx_fb_listing_raw_event_listed_at', table_name='facebook_listing_raw')
    op.drop_index('idx_fb_listing_raw_current_listing', table_name='facebook_listing_raw', postgresql_where=sa.text('valid_to IS NULL'))
    op.create_index(op.f('idx_raw_extract_run'), 'facebook_listing_raw', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('idx_raw_extract_event_listing'), 'facebook_listing_raw', ['event_id', 'fb_listing_id'], unique=False)
    op.create_index(op.f('idx_raw_extract_event_listed_at'), 'facebook_listing_raw', ['event_id', 'listed_at'], unique=False)
    op.create_index(op.f('idx_raw_extract_current_listing'), 'facebook_listing_raw', ['event_id', 'fb_listing_id'], unique=True, postgresql_where='(valid_to IS NULL)')
    # ### end Alembic commands ###
