"""change seatgeek module to only be a aggregated stats table

Revision ID: e6a689df000c
Revises: c81d98f60361
Create Date: 2026-09-04 17:43:22.716854

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'e6a689df000c'
down_revision: Union[str, None] = 'c81d98f60361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seatgeek_event_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_key', sa.String(length=64), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('sg_event_id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('lowest_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('highest_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('average_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('median_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('listing_count', sa.Integer(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='fk_sg_event_stats_event_id'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name='fk_sg_event_stats_run_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'stat_date', name='uq_sg_event_stats_event_date')
    )
    op.create_index('idx_sg_event_stats_run', 'seatgeek_event_stats', ['pipeline_run_id'], unique=False)
    op.drop_index(op.f('idx_sg_listing_raw_current_listing'), table_name='seatgeek_listing_raw', postgresql_where='(valid_to IS NULL)')
    op.drop_index(op.f('idx_sg_listing_raw_event_listing'), table_name='seatgeek_listing_raw')
    op.drop_index(op.f('idx_sg_listing_raw_run'), table_name='seatgeek_listing_raw')
    op.drop_table('seatgeek_listing_raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seatgeek_listing_raw',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sg_listing_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sg_event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('section', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('row', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_per_ticket', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('deal_score', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=True),
    sa.Column('delivery_methods', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('valid_from', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('valid_to', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_sg_listing_raw_event_id')),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name=op.f('fk_sg_listing_raw_run_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('seatgeek_listing_raw_pkey'))
    )
    op.create_index(op.f('idx_sg_listing_raw_run'), 'seatgeek_listing_raw', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('idx_sg_listing_raw_event_listing'), 'seatgeek_listing_raw', ['event_id', 'sg_listing_id'], unique=False)
    op.create_index(op.f('idx_sg_listing_raw_current_listing'), 'seatgeek_listing_raw', ['event_id', 'sg_listing_id'], unique=True, postgresql_where='(valid_to IS NULL)')
    op.drop_index('idx_sg_event_stats_run', table_name='seatgeek_event_stats')
    op.drop_table('seatgeek_event_stats')
    # ### end Alembic commands ###
